### ISSUE TITLE
Support redirects

### ISSUE THREAD

**Issue by litrik** [lexs/webimageloader#11]
Images that are being redirected fail to load.

Example:

Loading the URL http://api.twitter.com/1/users/profile_image?screen_name=bdesmet_&size=bigger fails with the following error message:

09-18 20:37:20.653: D/skia(16308): --- SkImageDecoder::Factory returned null
09-18 20:37:20.669: D/ImageHelper(16308): Error loading bitmap
09-18 20:37:20.669: D/ImageHelper(16308): java.io.IOException: Failed to create bitmap, decodeStream() returned null
09-18 20:37:20.669: D/ImageHelper(16308):   at com.webimageloader.util.BitmapUtils.decodeStream(BitmapUtils.java:42)
09-18 20:37:20.669: D/ImageHelper(16308):   at com.webimageloader.loader.PendingRequests$RequestListener.onStreamLoaded(PendingRequests.java:144)
09-18 20:37:20.669: D/ImageHelper(16308):   at com.webimageloader.loader.NetworkLoader.loadInBackground(NetworkLoader.java:94)
09-18 20:37:20.669: D/ImageHelper(16308):   at com.webimageloader.loader.BackgroundLoader$1.run(BackgroundLoader.java:22)
09-18 20:37:20.669: D/ImageHelper(16308):   at com.webimageloader.concurrent.ListenerFuture.run(ListenerFuture.java:21)
09-18 20:37:20.669: D/ImageHelper(16308):   at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:442)
09-18 20:37:20.669: D/ImageHelper(16308):   at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
09-18 20:37:20.669: D/ImageHelper(16308):   at java.util.concurrent.FutureTask.run(FutureTask.java:137)
09-18 20:37:20.669: D/ImageHelper(16308):   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
09-18 20:37:20.669: D/ImageHelper(16308):   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
09-18 20:37:20.669: D/ImageHelper(16308):   at java.lang.Thread.run(Thread.java:856)
09-18 20:37:20.669: D/ImageHelper(16308):   at com.webimageloader.util.PriorityThreadFactory$1.run(PriorityThreadFactory.java:26)

If you load the URL to which the first URL redirects (https://si0.twimg.com/profile_images/1593219329/333834_10150325451617266_569922265_8295088_379754916_o_bigger.jpg) everything works fine.

**Comment by lexs** [comment]
We do follow redirects but the problem here is that the redirect is from http to https. Here is a StackOverflow post (and Java bug) about this http://stackoverflow.com/a/1884427/253583.

If you change the original url to use https it works for example. Do you think we should manually handle redirects from http to https anyways?

**Comment by orrc** [comment]
I'm trying to use redirects (from HTTP to HTTP) and they're not working, and I can't see in the code anywhere where redirects are considered. I get the same stacktrace above, and I can see that no second network is being sent.

I call `HttpURLConnection.setFollowRedirects(true);` before attempting to load any images.

The only slightly different thing is that the server I'm using is returning HTTP 307 redirects (rather than the more oft-used 301 or 302).

What have I missed? :)

**Comment by orrc** [comment]
The answer seems to be the HTTP 307 status code.
http://b.android.com/41739 indicates that the 307 status code isn't properly handled.

I tested this library with the Twitter API URL above (though went from HTTPS to HTTPS) and it worked great.

**Comment by lexs** [comment]
The library relies on HttpUrlConnection to handle redirects (which it does by default).

I don't think this it's possible to work around this issue as-is, however I could modify ConnectionHandler to allow for returning a new UrlConnection so you could work around this. Do you want this?

https://github.com/lexs/webimageloader/blob/master/webimageloader/src/main/java/com/webimageloader/ConnectionHandler.java

**Comment by orrc** [comment]
Yeah, that sounds good.

I've been thinking about integrating OkHttp anyway, since it fixes some other Android HTTP bugs that I need to deal with. So this would probably work out.

**Comment by lexs** [comment]
I wonder if it would be better to actually change the signature to take an URL so your free to use OkHttp if you want instead of having to just throw a connection away? It would still only be called for http(s) though.

**Comment by orrc** [comment]
Sounds like a good idea to me!

**Comment by mecid** [comment]
is this issue fixed in latest maven build?

**Comment by orrc** [comment]
@mecid Which issue specifically? Redirects already work fine with this library; 307 redirects don't work, but that's an Android bug (which I solved by using pull request #17 and OkHttp).

**Comment by mecid** [comment]
@orrc this your pull request included in latest maven build?

**Comment by orrc** [comment]
@mecid No, the pull request is open; there hasn't been any discussion about it so far. I compiled my own JAR from source.

**Comment by lexs** [comment]
It's not merged yet, in the meantime you can clone @orrc repo and compile it yourself.

**Comment by mecid** [comment]
I am using okhttp from your sample, but redirects not working.
