### ISSUE TITLE
Bypass Cache

### ISSUE THREAD

**Issue by bobz** [lexs/webimageloader#16]
Is there any way to bypass the cache explicitly and force the image to be downloaded?

**Comment by nikreiman** [comment]
You can set a max cache age of 1, but that would apply for all requests (and is also a bit hacky):

https://github.com/lexs/webimageloader/blob/master/webimageloader/src/main/java/com/webimageloader/ImageLoader.java#L503

**Comment by bobz** [comment]
Hi Nik,

Thanks for the feedback.

I ended up "closing" the cache, opening the underlying disk LRU, and removing the item manually.

Also a huge hack, but it works for now. ;)

Best,
Jay

**Comment by bobz** [comment]
Here's my code if you or anyone else is curious.

https://gist.github.com/bobz/ff1a3f28ac0ead18115c

Just need to make sure you re-initialize the imageLoader later.

Bear in mind, this works ok because this is a rare occurrence in my application, usually the default behavior is great.

**Comment by lexs** [comment]
There's currently no way of asking the library to bypass the cache but I'll look into adding it. Another workaround (that may not fit you) is adding a random query parameter to your url like ?cache-bust=1234.

**Comment by atomfrede** [comment]
So you mean when adding a custom query parameter the image is not delivered from the cache because it was saved with a different key before? Good to know :)
