### ISSUE TITLE
Disk Cache not cacheing last image

### ISSUE THREAD

**Issue by damianflannery** [lexs/webimageloader#19]
Just playing about with this under no network conditions and it seems that the last item to be fetched by the loader doesn't get committed to the disk cache.

Steps to reproduce:
1. Navigate to activity that uses webimageloader (e.g. listview activity)
2. Exit to home screen and remove app from recents launcher to evict from memory
3. Put phone into airplane mode
4. Navigate back to activity in 1. All images are fetched except one (usually the last image in the list)

(ddms says ImageLoader: Error loading bitmap)

**Comment by lexs** [comment]
The problem is that DiskLruCache didn't flush after each write to the cache, however in the next release it will, yay! https://github.com/JakeWharton/DiskLruCache/issues/37

**Comment by damianflannery** [comment]
Great, thanks for looking into it Alex.
