### ISSUE TITLE
Not possible to request images over HTTPS

### ISSUE THREAD

**Issue by condesales** [lexs/webimageloader#21]
The error occurs when trying to use a custom ConnectionFactory for HTTPS

I downloaded the code and found the error.
On constructor of class NetworkLoader is missing the code below
    this.connectionFactory = builder.connectionFactory

**Comment by lexs** [comment]
Fixed in 142d5ea1a4fce9d4c4a5aa38eacff846cb78a50b

**Comment by lexs** [comment]
Released
