### ISSUE TITLE
Not working with new version of DiskLRUChache

### ISSUE THREAD

**Issue by condesales** [lexs/webimageloader#22]
For some reason, when using the 1.1.6 version of webimageloader with 2.0.0 version of disklrucache, the project get noClassDefError exception

**Comment by lexs** [comment]
Yeah, DiskLruCache version 2.0.0 renamed the package so it won't work before this commit and vice verse: https://github.com/lexs/webimageloader/commit/2626ee47a9785c4ca8c88fd54564db2c3b89b556.

A new version with 2.0.0 as a dependency will be released this week probably.
