### ISSUE TITLE
Image from disk cache is without transparent background

### ISSUE THREAD

**Issue by liorix** [lexs/webimageloader#26]
Hi,

First I must say it's the best image loading library for android that I've found so far. Thanks for this awesome work!

I've tried to use it in my project, I'm using transformation to make the image rounded. Everything works amazing, but when the disk cache is enabled and the image being loaded from the cache, it's being displayed with black background instead of transparent background in the area that was clipped (attached picture).
![image](https://f.cloud.github.com/assets/1379349/838547/127ef214-f322-11e2-9921-dd9ae93d81a4.png)

Is it a configuration that I'm missing or a bug? BTW, in which format the image being saved in the cache, because if it's the same format as the original image and it doesn't support transparency, it might be the root for the problem.

Would love to get some help with that!
Thanks,
Lior

**Comment by lexs** [comment]
You can return the desired format in your transformation, see https://github.com/lexs/webimageloader/blob/master/webimageloader/src/main/java/com/webimageloader/transformation/Transformation.java#L28

**Comment by liorix** [comment]
Great. work like a  charm! Thanks for this really great work!

**Comment by liorix** [comment]
BTW, I think it's worth mentioning in the documentation section since it's a small change and I guess that many people are using the transformation to clip/round images.
Anyway. Thanks!
