### ISSUE TITLE
Custom header attributes for request

### ISSUE THREAD

**Issue by atomfrede** [lexs/webimageloader#6]
To support e.g. https basic auth mechnism or addtional header attributes that are required to gain access to an image resource it should be possible to add custom header parameters to the request.

**Comment by lexs** [comment]
Do you need to have different handlers on a per request basis or is a "global" handler ok? I think having separate handlers for each request is overengineering it, if that is really is needed it's always possible to do url matching in the handler itself.

**Comment by atomfrede** [comment]
For my usecase a global header would be perfect. I also guess a per request header is really too much and not required.

**Comment by atomfrede** [comment]
Cool great, thanks! I will test it as soon as possible, but it should work perfectly. I've hacked something similar in my local repo.
