### ISSUE TITLE
Create a class which inherits from AsyncTask for progress updates

### ISSUE THREAD

**Issue by arnaudbos** [lexs/webimageloader#9]
The idea is to have an AsyncTask to call to allow downloading one or several files with progress updates.

**Comment by lexs** [comment]
This is something I've "looked" at but it's quite hard to do properly while supporting it for transformations etc. I don't think inheriting AsyncTask would make much sense for example. It would probably be another method on the Listener instead. It's probably ok to only provide progress for http get's as a workaround too?

**Comment by arnaudbos** [comment]
Yes, the key idea is actually to get HTTP requests progress updates. I was thinking about AsyncTask because it already has simplified mechanics to publish this kind of information.
The simple use case is to use a progress bar while downloading one or more files (a `loadBlocking` inside an AsyncTask for instance).
